from driver import Driver


if (__name__ == "__main__"):
        robot1 = Driver() 
        while(True):
            robot1.forward()
            time.sleep(.2)
            robot1.right()
            time.sleep(1)
            robot1.backward()
            time.sleep(.2)
            robot1.backRight()
            time.sleep(1)
            robot1.forward()
            time.sleep(.2)
            robot1.right()
            time.sleep(1)
            robot1.backward()
            time.sleep(.2)
            robot1.backRight()
            time.sleep(1)
            robot1.stop()
            robot1.forward()
            time.sleep(.2)
            robot1.left()
            time.sleep(1)
            robot1.backward()
            time.sleep(.2)
            robot1.backLeft()
            time.sleep(1)
            robot1.forward()
            time.sleep(.2)
            robot1.left()
            time.sleep(1)
            robot1.backward()
            time.sleep(.2)
            robot1.backLeft()
            time.sleep(1)
            robot1.stop()
            time.sleep(6)
            robot1.forward()
            time.sleep(1)
	

